version: 0.2

env:
  variables:
    key: "value"
  variables:
    AWS_DEFAULT_REGION: ap-northeast-1   

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo installing...
      - aws --version
      - echo installed
  pre_build:
    commands:
      - echo pre_building...
      - aws configure set default.region $AWS_DEFAULT_REGION
      - aws cloudformation validate-template --template-body file://./cfn/vpc.yaml
      - echo pre_builded
  build:
    commands:
      - echo building...
      - echo builded
  post_build:
    commands:
      - echo post_building...
      - echo post_builded
artifacts:
  files:
    - "**/*"
  name: myname-$AWS_DEFAULT_REGION
